### PR TITLE
feat(typings): adapt to the new Vue typings

### PR DESCRIPTION
**Pull request by ktsn**
**Please do not merge this until https://github.com/vuejs/vue/pull/6391 is merged**

I'll update the deps in package.json when vuejs/vue#6391 is merged and released.

close #658

### CODE REVIEW

**Comment by yyx990803** [comment]
@ktsn cool! There's also a stale PR for vue-router: https://github.com/vuejs/vue-router/pull/1204 would you mind reviewing it?

**Comment by ktsn** [comment]
@yyx990803 Ah, I actually also created a PR for vue-router https://github.com/vuejs/vue-router/pull/1685. Forgot to send ping to you 😄

**Comment by yyx990803** [comment]
Ah nice :D

**Comment by HerringtonDarkholme** [comment]
Ping @ktsn  would you like to resolve the conflict and change vue repository to dev branch in vuejs org? Thanks!

**Comment by ktsn** [comment]
Done!

**Pull request merged**
