### PR TITLE
[DOC KR] update updated Api description

### PR DESCRIPTION
**Pull request by bichikim**
- Component Binding Helpers
- registerModule

### CODE REVIEW

**Comment by LinusBorg** [comment]
@phanan can you take a look?

**Comment by kazupon** [comment]
@ChangJoo-Park Can you review it?

**Comment by ChangJoo-Park** [comment]
@kazupon  thanks for ping to me. 

I'll review this pr 

@bichikim 감사합니다 👍

**Comment by phanan** [comment]
@LinusBorg I don't speak a single word of Korean 😄

**Pull request merged**
