### PR TITLE
Eliminate extra word

### PR DESCRIPTION
**Pull request by dcrall**
"You can ~do~ achieve this" -> "You can achieve this"

### CODE REVIEW

**Comment by ktsn** [comment]
Thanks for making the PR. However, `do + verb` looks valid English. It is used for emphasis.
https://www.usingenglish.com/forum/threads/166197-I-do-verb

**Comment by dcrall** [comment]
The example you sited is **I do** + verb, which is primarily a conversational construct. This edit does not match that pattern, and I can assure you it does not read as correct English. It is awkward, redundant, and adds no clarity to the statement

**Comment by dcrall** [comment]
Plus, in this sentence, you have three verbs: can, do, and achieve. That is another reason it doesn't match the pattern in the link.

**Comment by ktsn** [comment]
I see. Thank you for clarifying.

**Pull request merged**
