### PR TITLE
wording did not make sense.

### PR DESCRIPTION
**Pull request by playpianolikewoah**
> Actions don't

Did not make sense.

### CODE REVIEW

**Comment by posva** [comment]
Thanks for your interest in helping the docs, but that is valid English 🙂

_The sky is blue, the sun isn't_

**Comment by playpianolikewoah** [comment]
@posva, I understand what the intention is, however, it is not valid English. When I first read it, it confused me.

I the docs said: 
> mutations have to be synchronous. Actions don't

It would make sense. 
Also the abruptness of the second sentence will confuse the reader, as it did me. 
Also the example you gave when you closed this PR is not the same structure. 

The main reason it doesn't make sense is if you complete the sentence. 

> Well, remember that **mutations must be synchronous**? Actions don't must be synchronous. 

Changing the "must" to "have" and completing the sentence you get: 

> Well, remember that **mutations have to be synchronous**? Actions don't have to be. 

Or as I suggested also works without changing the first sentence. 

Either way the second sentence is unnecessarily abrupt.

**Comment by posva** [comment]
You mean it could be

> Well, remember that mutations must be synchronous? Actions mustn't
?

I personally think adding  _be synchrounous_ at the end makes the sentence heavy but I'm not native. WDYT @chrisvfritz @yyx990803

**Comment by playpianolikewoah** [comment]
@posva That is an option. However, I offered other options that sound better, IMO. 
I personally think: 
> mutations have to be synchronous. Actions don't. 

Is the easiest fix.

**Comment by chrisvfritz** [comment]
@posva I might be late, but I like that as well. 🙂 

> mutations have to be synchronous. Actions don't.

**Pull request merged**
