### PR TITLE
Fixed symlink problem on Windows & translate docs to zh-cn

### PR DESCRIPTION
**Pull request by jingsam**

### CODE REVIEW

**Comment by jingsam** [comment]
Symlinks are not working on Windows

**Comment by ktsn** [comment]
Why would you want the docs to work on Windows?
It seems that there are no reason to do that because we can read it on the web with any OS.
And it will increase maintenance cost without symlink...

In addition, we cannot merge the PR that includes two or more large fixes, please separate them.

**Comment by jingsam** [comment]
I am working on translating this docs to a Chinese version and almost fininshed. I am a Windows user. Symlinks can not compile by gitbook on Windows. What'more, the contents of book.json in en and zh-cn version are different. So you need seperate them rather than using symlinks.

**Comment by jingsam** [comment]
Does that make sense? @ktsn If it does, I have send another PR #406

**Comment by jingsam** [comment]
@ktsn I have finished the Chinese version docs. Maybe you can  invite someone to review it, thanks

**Comment by yyx990803** [comment]
Merged as eaf53da - thank you!

**Pull request closed without merging**
