### PR TITLE
chore: migrate to CircleCI 2 and add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Please check if the config is correct and that I did not forget anything =)

**Comment by gcoguiec** [comment]
@ktsn Do you think we can close this one since #1372 has been merged ?

**Comment by DanielRuf** [comment]
Node 10 is still missing there.

**Comment by ktsn** [comment]
Closing as #1372 has been merged. For the reason not include both nodejs version, it's discussed [here](https://github.com/vuejs/vuex/pull/1372#issuecomment-417830957).
Thank you for your PR anyway!

**Pull request closed without merging**
