### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by dear-lizhihua**
fix `Error: Couldn't locate plugins "edit-link, prism, github, theme-vuejs", Run 'gitbook install' to install plugins from registry.`

### CODE REVIEW

**Comment by chrisvfritz** [comment]
Since we use Gitbook for so many repos, I wonder if it'd actually be good to extract some common config/build process out into a package. Not volunteering, but putting the idea out there... 😅

**Comment by chrisvfritz** [comment]
Actually, I wonder if this is a job that calls for @atomaka. 😉 

Server Superhero

**Comment by dear-lizhihua** [comment]
I encountered a mistake when I started the project. I looked at the configuration of vue-router, it's OK. So I created this issue.

**Comment by yyx990803** [comment]
I made the same fix when I was updating the docs, but thanks for the PR!

**Pull request closed without merging**
