### PR TITLE
Update state.md

### PR DESCRIPTION
**Pull request by jasba24**
Fix typo in the doc

### CODE REVIEW

**Comment by cuebit** [comment]
Thanks for the PR but I’m afraid this is not a typo.

**Comment by jasba24** [comment]
Oh yes, I see that it is not a typo, but I think it would be better to put a point in the letters to be more specific and help people who know little English

**Comment by jasba24** [comment]
I mean something like that **i.e**

**Comment by cuebit** [comment]
@jasba24 yes, I think that does add clarity. If you push that change to this PR, I'm happy to re-open it?

**Pull request closed without merging**
