### PR TITLE
[docs:korean] Migrate git-book to vuepress

### PR DESCRIPTION
**Pull request by usolkim**
- korean docs migrate to vuepress
- api reference doc updated

@ChangJoo-Park is reviewed.

### CODE REVIEW

**Comment by usolkim** [comment]
- add Promise in Installation document
- add Method-Style Access in getters document
- add Namespace in module document
- plugins document is updated
- testing document is updated

**Comment by yyx990803** [comment]
Could you please resolve the conflict (just merged the RU translation)

**Comment by usolkim** [comment]
merged!

**Comment by usolkim** [comment]
@yyx990803 merge to dev branch please

**Pull request merged**
