### PR TITLE
docs: Patch preserveState option usage

### PR DESCRIPTION
**Pull request by theneverstill**

### CODE REVIEW

**Comment by kiaking** [comment]
Thanks for the PR! I think this is true, but in that case we should fixing the [SSR docs at this section](https://ssr.vuejs.org/guide/data.html#store-code-splitting) as well.

@ktsn Could you double check if its true where we should call `{ preserveState: false }` on server side and `{ preserveState: true }` at the client side?

**Comment by ktsn** [comment]
Yes that's right.

**Comment by kiaking** [comment]
I've opened PR at https://github.com/vuejs/vue-ssr-docs/pull/281. Let's see how it goes.

**Comment by kiaking** [comment]
This has been taking care of at the https://github.com/vuejs/vue-ssr-docs/pull/281#event-3339547032 👍

**Comment by yooouuri** [comment]
How can I set `preserveState` to false on the client and true on the server if I register my components trough the contructor?


```
const stores = {
  ...
}

export function createStore() {
  const modules = {}

  for (const namespace in stores) {
    modules[namespace] = {
      namespaced: true,
      ...stores[namespace],
    }
  }

  return _createStore<State>({
    modules,
    devtools: false,
    plugins: [vuexLocal.plugin],
  })
}
```

**Pull request closed without merging**
