### PR TITLE
Added Italian Translation

### PR DESCRIPTION
**Pull request by ludo237**
Hello everyone.

I would like to propose this WIP based on the demand from a part of the Italian Community. The more people are using vuex the more requests I got for an Italian translation so here we go.

I'd like to finish this for monday, the doc is pretty short compared to the vuejs one. What do you think?

### CODE REVIEW

**Comment by yyx990803** [comment]
Let me know if you think it's ready to merge. I can't read Italian though, so if you want you should mention someone who can review it for you :)

**Comment by ludo237** [comment]
It's not ready yet, missing some docs. I'm reviewing it with a colleague of mine.

**Comment by ludo237** [comment]
60% done. I'm taking it slowly for a better review process

**Comment by ludo237** [comment]
@yyx990803 100% translated and reviewed. Merge when you want!

**Comment by yyx990803** [comment]
Great, thanks for the hard work!

**Comment by ludo237** [comment]
No problem Next challenge is to contribute to Vuejs itself :)

**Pull request merged**
