### PR TITLE
build: fix type exporting

### PR DESCRIPTION
**Pull request by trim21**
fix wrong package.json exports field

re-production: https://github.com/trim21/vuex-ts-bug

### CODE REVIEW

**Comment by mauricewegner** [comment]
Related: https://github.com/microsoft/TypeScript/issues/52363 and https://github.com/microsoft/TypeScript/issues/49160#issuecomment-1137482639

**Comment by jacobtshirt** [comment]
Can we get some movement on this?

**Comment by trim21** [comment]
Looks like vuex doesn't accept such PR now, feel free to cherry-pick from it and create a new one if someone need this get merged.

**Comment by weier910** [comment]
你的邮件我已收到！

**Pull request closed without merging**
