### PR TITLE
Add language pt-br

### PR DESCRIPTION
**Pull request by DavidWilliamBalbino**

### CODE REVIEW

**Comment by ErickPetru** [comment]
I took a look and saw that this translation is ok. Since it's more up to date than the https://github.com/vuejs/vuex/pull/823 I think this pull request should be merged.

**Comment by ktsn** [comment]
Hmm, we cannot merge this PR now since it does not follow the file name convention (all md file has extra suffix `- br`) and looks like the `installation.md` is broken. Also we need to update `LANGS.md` to let gitbook process `pt-br` translation.

@DavidWilliamBalbino Could you fix the above points?

Or it would be appreciated if @ErickPetru can take this over.

**Comment by periscuelo** [comment]
Thank you so much for quick response. I want to help to merge it so soon wich possible. But i don't know if @DavidWilliamBalbino have time to make the fix points. I don't want the credit's for the translation. I want only help to merge it. How can i help? It's a problem if i make other pull with this fix? Can i make it and the translation credits goes to David? Thanks again for looking at this pullrequest.

**Comment by ErickPetru** [comment]
@periscuelo don't bother with it, I believe we're a strong and participative community, everyone's help is valuable. In my humild own opinion, individual credits are the less important part.

**Comment by periscuelo** [comment]
That's good, @ErickPetru . Well being so I believe that I was able to make the adjustments. I hope I contributed. I just changed what ktsn asked for.

**Comment by ktsn** [comment]
I just merged #1238. If you want to improve it, please make a new PR.

Thanks a lot for your help!

**Pull request closed without merging**
