### PR TITLE
Fix minor errors in README.md

### PR DESCRIPTION
**Pull request by dollinad**
Changes involve:
- Removal of dead links: data flow.png and vuex.png
- Removal of discourse markers (although, also, in addition) to make sentences precise

### CODE REVIEW

**Comment by ktsn** [comment]
> Removal of dead links

Well, it's not dead links actually. https://vuex.vuejs.org/

**Comment by dollinad** [comment]
Updated!

Re-added link https://vuex.vuejs.org/

**Comment by ktsn** [comment]
I mean `flow.png` and `vuex.png` is not dead links. Could you restore them?
You can see the rendered docs of this PR in https://deploy-preview-1523--vuex-docs.netlify.com/ or by `npm run docs` in your local.

**Comment by ktsn** [comment]
Merged. Thanks!

**Pull request merged**
