### PR TITLE
Proposal: add options.meta to mutation passed to store.subscribe() #1035

### PR DESCRIPTION
**Pull request by thebrubaker**
Pull request for the solution described on issue #1035 
- added `options.meta` to mutation object passed to subscribers.
- updated docs describing `options.meta` for plugin developers

### CODE REVIEW

**Comment by thebrubaker** [comment]
@ktsn updated with reversions to dist and added a separate test.

**Comment by guiferrpereira** [comment]
+1

**Comment by mlavina** [comment]
@ktsn  @thebrubaker 

Any updates on this front. My team has an app transitioning from a custom Flux implementation to Vuex and we rely on the Flux standard action `meta` field. This seems to be the equivalent. 

Thanks,
Michael

**Comment by Kangoula** [comment]
Hello, 2 years after is there any updates on this PR ?
This feature might resolve some issues I'm facing.

Thanks,
Guillaume

**Comment by kiaking** [comment]
This PR might be too old to resolve the conflict. Though in the issue #1035 discussion, it seems like a valid thing. @thebrubaker would it be possible to finalize this PR with the latest branch?

**Comment by thebrubaker** [comment]
Ya if I find some time this week I'm happy to try to get this updated to the latest branch.

**Comment by kiaking** [comment]
That's wonderful 🙌  Thanks a lot 👍

**Comment by kiaking** [comment]
@thebrubaker Hi! Do you have any update on this one?

**Comment by kiaking** [comment]
OK I'll be closing the PR due to inactivity. Please feel free to reopen it when you have time to work on to it! Just making sure the issues and PRs are healthy as possible 👍

**Comment by thebrubaker** [comment]
That makes sense, sorry didn't have a chance to work on this and I likely won't be able to in the near future, but hopefully the example can help those seeking this addition with what they need to do!

**Comment by kiaking** [comment]
Yea thank you so much for your help including the discussions at the issue as well 👍

**Pull request closed without merging**
