### PR TITLE
Fix getter type optional params

### PR DESCRIPTION
**Pull request by kootoopas**
Fix getter type to match implementation by marking optional params.

### CODE REVIEW

**Comment by kootoopas** [comment]
Node dependency error in deploy preview step:
```
5:34:36 PM: error mkdirp@1.0.3: The engine "node" is incompatible with this module. Expected version ">=10".
```

**Comment by kiaking** [comment]
Thanks for the contribution! Though, all arguments to getters are not optional (`undefined`). The argument is always passed to the getters. You can try it out by console logging all arguments.

**Comment by kootoopas** [comment]
I see, just checked it out...

**Comment by kootoopas** [comment]
Although I still believe that the user should not be forced to provide all 4 args when they want to use a subset.

**Comment by kiaking** [comment]
@kootoopas Maybe. But it's needed in fact. And the underscore prefix in TS such as `_getter` are there for that reason.

**Pull request closed without merging**
