### PR TITLE
[docs] Align GitBook theming to main Vue.js site

### PR DESCRIPTION
**Pull request by pearofducks**
One of the strengths Vue highlights is that these extra plugins are maintained by the core team. With this change, the documentation feels a lot more like this is true. :)

Note the lack of chapter numbers is not my doing, that seems to possibly be a change from GitBook 2 to 3 - but I do think it's better without them.

> edit// Also, I'd recommend bumping the GitBook version in `book.json` if possible to `>3.0.0`, I couldn't get the current version to run locally. Let me know if this an OK change and I can add it here.

before

after

### CODE REVIEW

**Comment by ktsn** [comment]
Looks good to me.
@yyx990803 What do you think?

**Comment by kazupon** [comment]
awesome. 💯 
if this theme is provided as the gitbook plugin, we can use it into the other vue docs.
we should be made the gitbook theme plugin.

**Comment by yyx990803** [comment]
This is great! And +1 to what @kazupon said

**Comment by pearofducks** [comment]
Plugin made! This applies the css globally - except the language-selection screen (a limitation of GitBook).

**Comment by yyx990803** [comment]
@pearofducks thank you so much! Would appreciate PRs for vue-router and vue-loader as well :)

**Pull request merged**
