### PR TITLE
Adding Portuguese Translation for Vuex

### PR DESCRIPTION
**Pull request by vitorarjol**
The complete documentation was translated and revised for Portuguese.

Sorry for the number of commits. I was using gitbook to review the format of the files and it created a lot of commits.

Hope it helps Vue and Vuex to expand the users!

### CODE REVIEW

**Comment by blake-newman** [comment]
Thumbs up to you! If you have experience with git you can squash the commits.  If not I'm sure someone on thee team can squash it before it gets merged.

**Comment by vitorarjol** [comment]
@blake-newman Well, I had no experience with squash commits before, but looks like that it worked! Much better now :)

**Comment by yyx990803** [comment]
Could you please use English for the commit messages?

The easy way to turn it into one commit:

``` bash
git reset THE_COMMIT_BEFORE_YOU_CHANGED_ANYTHING
git add -A
git commit -m 'Add Portuguese translation'
git push -f
```

**Comment by vitorarjol** [comment]
Done!

**Comment by yyx990803** [comment]
:tada:

**Pull request merged**
